#!/usr/bin/env python3
# odometry.py — dead-reckoning pose estimator (Phase 5).
#
# Fuses STM32 encoder feedback (wheel RPM, via uart_link.STM32Link) with
# imu.py's absolute IMU heading into a running (x, y, yaw) estimate in a
# compass-referenced local frame — same dead-reckoning approach the old
# BBB scripts used (Old_files/dev_bak/ugv_pid_waypoint.py): distance comes
# from the wheels, heading comes DIRECTLY from the IMU's fused output (not
# integrated step-by-step), since that's immune to wheel-slip heading
# error in a way pure differential odometry isn't.
#
# Coordinate convention: standard math convention, CCW-positive, matching
# the Ackermann sign convention already documented in ackermann_config.h
# (positive steering angle = left turn = CCW). The x-axis is whatever
# heading the IMU reports as the reference (0 deg) at reset() time —
# "compass-referenced" in the sense that it's locked once per mission
# rather than re-derived from the path's own direction of travel, so a
# pattern generated by waypoints.py keeps the same real-world orientation
# every time it's run, as discussed in scratchpad.md.
#
# NOTE: this accumulates drift over distance/time with no absolute
# correction (no RTK on this rover) — unlike Old_files/UGV_closed's RTK
# system, position accuracy here degrades the longer a mission runs. This
# is a deliberate, understood trade-off, not a bug.

import math


def _wrap_to_pi(angle):
    return math.atan2(math.sin(angle), math.cos(angle))


def _compass_to_math_rad(heading_deg):
    """Compass heading (degrees, clockwise from North) -> standard math
    radians (CCW from the +X axis). Same conversion
    Old_files/UGV_closed/localization.py used for RTK heading; reused here
    for the IMU's compass-style heading output."""
    return math.radians((90.0 - heading_deg) % 360.0)


class Pose:
    __slots__ = ("x", "y", "yaw", "valid")

    def __init__(self, x=0.0, y=0.0, yaw=0.0):
        self.x = x
        self.y = y
        self.yaw = yaw
        self.valid = False


class Odometry:
    def __init__(self, imu, wheel_radius_m):
        self._imu = imu
        self._wheel_radius_m = wheel_radius_m
        self._pose = Pose()
        self._yaw_ref = None  # IMU heading captured as this mission's 0-reference

    def reset(self, x=0.0, y=0.0):
        """Re-zero position AND re-lock the heading reference — call this
        at the start of each mission (not just __init__), so "heading 0"
        is always wherever the rover is pointed when that mission begins,
        matching the old scripts' per-run yaw_start lock."""
        self._pose.x = x
        self._pose.y = y
        self._pose.valid = False
        self._yaw_ref = None

    def update(self, rpm_L, rpm_R, dt_s):
        """Call once per control-loop tick with the STM32's latest
        rpm_L/rpm_R (FeedbackData.rpm_L/rpm_R from uart_link.py) and the
        elapsed time since the previous call. Returns the updated Pose
        (also available via .pose)."""
        imu_data = self._imu.read()

        # Heading: directly from the IMU's fused output, not integrated.
        # imu.py already holds the last-good value across transient I2C
        # glitches on its own, so this stays sane even on a bad tick.
        yaw_math = _compass_to_math_rad(imu_data.heading_deg)
        if self._yaw_ref is None:
            self._yaw_ref = yaw_math
        self._pose.yaw = _wrap_to_pi(yaw_math - self._yaw_ref)

        # Distance: average of both wheels, from encoder RPM (STM32-measured,
        # positive = forward per rpi_link.c's feedback frame convention).
        v_L = (rpm_L / 60.0) * 2.0 * math.pi * self._wheel_radius_m
        v_R = (rpm_R / 60.0) * 2.0 * math.pi * self._wheel_radius_m
        d_center = ((v_L + v_R) / 2.0) * dt_s

        self._pose.x += d_center * math.cos(self._pose.yaw)
        self._pose.y += d_center * math.sin(self._pose.yaw)
        self._pose.valid = imu_data.valid

        return self._pose

    @property
    def pose(self):
        return self._pose


if __name__ == "__main__":
    # Standalone sanity check with a fake IMU (no hardware needed): drive
    # "forward" at a constant yaw for 10 ticks at 1 m/s-equivalent RPM and
    # confirm x advances roughly as expected, y stays ~0.
    import rover_config as cfg

    class _FakeIMUData:
        heading_deg = 90.0  # compass 90 deg (East) -> math 0 rad -> +X
        valid = True

    class _FakeIMU:
        def read(self):
            return _FakeIMUData()

    rpm_for_1ms = (1.0 * 60.0) / (2.0 * math.pi * cfg.WHEEL_RADIUS_M)
    odo = Odometry(_FakeIMU(), cfg.WHEEL_RADIUS_M)
    odo.reset()
    for _ in range(10):
        p = odo.update(rpm_for_1ms, rpm_for_1ms, dt_s=0.05)
    print(f"After 10 ticks @1m/s, dt=0.05s: x={p.x:.3f} y={p.y:.3f} "
          f"yaw={math.degrees(p.yaw):.1f} (expect x~0.5, y~0.0, yaw~0.0)")
