#!/usr/bin/env python3
# odometry.py — dead-reckoning pose estimator (Phase 5).
#
# Fuses STM32 encoder feedback (wheel RPM, via uart_link.STM32Link) with
# imu.py's absolute IMU heading into a running (x, y, yaw) estimate in a
# compass-referenced local frame — same dead-reckoning approach the old
# BBB scripts used (Old_files/dev_bak/ugv_pid_waypoint.py): distance comes
# from the wheels, heading comes DIRECTLY from the IMU's fused output (not
# integrated step-by-step), since that's immune to wheel-slip heading
# error in a way pure differential odometry isn't.
#
# Coordinate convention: standard math convention, CCW-positive, matching
# the Ackermann sign convention already documented in ackermann_config.h
# (positive steering angle = left turn = CCW). The x-axis is whatever
# heading the IMU reports as the reference (0 deg), LOCKED FROM THE
# CIRCULAR MEAN of the first HEADING_LOCK_SAMPLES IMU readings the first
# time update() is called on this Odometry instance — i.e. once per
# mission.py process, not once per mission (see rover_config.py's
# HEADING_LOCK_SAMPLES comment for why this is an average, not one
# sample). reset() only re-zeros POSITION, it deliberately does not touch
# the heading reference (see reset()'s docstring for why this matters) —
# so every mission run within one mission.py session shares the same
# real-world orientation, which is the whole point of "compass-referenced"
# over "start-relative": a pattern generated by waypoints.py keeps the
# same field orientation across repeated test runs, not just within a
# single run. Point the rover the direction you want the pattern's +X
# axis to face BEFORE starting mission.py, not before each individual
# AUTO engagement — and keep it stationary during that first ~1.5s so the
# averaging window isn't itself capturing motion.
#
# NOTE: this accumulates drift over distance/time with no absolute
# correction (no RTK on this rover) — unlike Old_files/UGV_closed's RTK
# system, position accuracy here degrades the longer a mission runs. This
# is a deliberate, understood trade-off, not a bug.

import math

import rover_config as cfg


def _wrap_to_pi(angle):
    return math.atan2(math.sin(angle), math.cos(angle))


def _circular_mean(angles_rad):
    """Mean of a list of angles, handling 0/360 (2*pi) wraparound correctly
    — a naive arithmetic mean breaks near the wrap boundary (e.g. mean of
    359 deg and 1 deg should be 0 deg, not 180 deg)."""
    s = sum(math.sin(a) for a in angles_rad)
    c = sum(math.cos(a) for a in angles_rad)
    return math.atan2(s, c)


def _compass_to_math_rad(heading_deg):
    """Compass heading (degrees, clockwise from North) -> standard math
    radians (CCW from the +X axis). Same conversion
    Old_files/UGV_closed/localization.py used for RTK heading; reused here
    for the IMU's compass-style heading output."""
    return math.radians((90.0 - heading_deg) % 360.0)


class Pose:
    __slots__ = ("x", "y", "yaw", "valid")

    def __init__(self, x=0.0, y=0.0, yaw=0.0):
        self.x = x
        self.y = y
        self.yaw = yaw
        self.valid = False


class Odometry:
    def __init__(self, imu, wheel_radius_m):
        self._imu = imu
        self._wheel_radius_m = wheel_radius_m
        self._pose = Pose()
        self._yaw_ref = None  # IMU heading captured as this mission's 0-reference
        self._yaw_lock_samples = []  # raw yaw_math readings, while locking the reference
        self.last_imu_data = None  # full imu.IMUData from the most recent update() — for logging

    def reset(self, x=0.0, y=0.0):
        """Re-zero POSITION ONLY — call this at the start of each mission
        (mission.py does, on every SWB MANUAL->AUTO transition). Does NOT
        touch the heading reference: if it did, a pattern re-run later in
        the same session would face whatever direction the rover happened
        to be pointed at THAT restart, not the direction it faced the
        first time — defeating the reason "compass-referenced" was chosen
        over "start-relative" in the first place (see the module
        docstring, and the conversation this was caught in). The heading
        reference locks exactly once, the first time update() is ever
        called on this instance; restart mission.py itself to get a new
        one."""
        self._pose.x = x
        self._pose.y = y
        self._pose.valid = False

    def update(self, rpm_L, rpm_R, dt_s):
        """Call once per control-loop tick with the STM32's latest
        rpm_L/rpm_R (FeedbackData.rpm_L/rpm_R from uart_link.py) and the
        elapsed time since the previous call. Returns the updated Pose
        (also available via .pose)."""
        imu_data = self._imu.read()
        self.last_imu_data = imu_data  # exposed for the caller to log raw IMU fields

        # Heading: directly from the IMU's fused output, not integrated.
        # imu.py already holds the last-good value across transient I2C
        # glitches on its own, so this stays sane even on a bad tick.
        yaw_math = _compass_to_math_rad(imu_data.heading_deg)

        if self._yaw_ref is None:
            # Still locking the reference: average HEADING_LOCK_SAMPLES
            # readings (circular mean — see module docstring/rover_config.py)
            # instead of trusting a single noisy instant. Hold position at
            # (0,0) and report the pose invalid until the lock completes —
            # the rover is expected to be stationary during this window.
            self._yaw_lock_samples.append(yaw_math)
            if len(self._yaw_lock_samples) < cfg.HEADING_LOCK_SAMPLES:
                self._pose.valid = False
                return self._pose
            self._yaw_ref = _circular_mean(self._yaw_lock_samples)
            self._yaw_lock_samples = None  # done, free it

        self._pose.yaw = _wrap_to_pi(yaw_math - self._yaw_ref)

        # Distance: average of both wheels, from encoder RPM (STM32-measured,
        # positive = forward per rpi_link.c's feedback frame convention).
        v_L = (rpm_L / 60.0) * 2.0 * math.pi * self._wheel_radius_m
        v_R = (rpm_R / 60.0) * 2.0 * math.pi * self._wheel_radius_m
        d_center = ((v_L + v_R) / 2.0) * dt_s

        self._pose.x += d_center * math.cos(self._pose.yaw)
        self._pose.y += d_center * math.sin(self._pose.yaw)
        self._pose.valid = imu_data.valid

        return self._pose

    @property
    def pose(self):
        return self._pose


if __name__ == "__main__":
    # Standalone sanity checks with a fake IMU (no hardware needed).

    class _FakeIMU:
        def __init__(self, heading_deg):
            self.heading_deg = heading_deg

        def read(self):
            return type("D", (), {"heading_deg": self.heading_deg, "valid": True})()

    rpm_for_1ms = (1.0 * 60.0) / (2.0 * math.pi * cfg.WHEEL_RADIUS_M)

    # Check 0: the heading reference now locks over HEADING_LOCK_SAMPLES
    # ticks (circular mean), not a single sample — confirm the pose stays
    # invalid and unmoved for those ticks, and only starts advancing once
    # the lock completes, using a heading that JITTERS around 90 deg (not
    # a constant) to prove averaging is actually happening, not just
    # accepting the first sample.
    import random
    random.seed(0)
    imu = _FakeIMU(heading_deg=90.0)
    odo = Odometry(imu, cfg.WHEEL_RADIUS_M)
    for i in range(cfg.HEADING_LOCK_SAMPLES - 1):
        imu.heading_deg = 90.0 + random.uniform(-5.0, 5.0)
        p = odo.update(rpm_for_1ms, rpm_for_1ms, dt_s=0.05)
        assert not p.valid, f"pose reported valid before the heading lock completed (tick {i})"
        assert p.x == 0.0 and p.y == 0.0, "pose moved during the heading-lock window"
    imu.heading_deg = 90.0 + random.uniform(-5.0, 5.0)
    p = odo.update(rpm_for_1ms, rpm_for_1ms, dt_s=0.05)
    print(f"Check 0 (heading lock over {cfg.HEADING_LOCK_SAMPLES} jittery "
          f"samples): yaw={math.degrees(p.yaw):+.2f} (expect small, near 0 "
          f"— the jitter should mostly average out, not just take the last "
          f"sample)")

    # Check 1: drive forward for 10 ticks at 1 m/s (AFTER the heading lock,
    # using a steady heading now), confirm x advances, y stays ~0, yaw
    # reads ~0 (heading == the locked reference).
    imu = _FakeIMU(heading_deg=90.0)  # compass 90 deg (East) -> math 0 rad -> +X
    odo = Odometry(imu, cfg.WHEEL_RADIUS_M)
    for _ in range(cfg.HEADING_LOCK_SAMPLES):
        odo.update(0.0, 0.0, dt_s=0.05)  # complete the heading lock, stationary
    for _ in range(10):
        p = odo.update(rpm_for_1ms, rpm_for_1ms, dt_s=0.05)
    print(f"Check 1 (drive 0.5m): x={p.x:.3f} y={p.y:.3f} "
          f"yaw={math.degrees(p.yaw):.1f} (expect x~0.5, y~0.0, yaw~0.0)")

    # Check 2: reset() position only, then simulate the rover having
    # physically turned to face a NEW direction (heading_deg changes) —
    # confirm reset() does NOT re-lock the reference: yaw should now
    # report the real ~90 deg turn, not silently re-zero to match it.
    odo.reset()
    imu.heading_deg = 180.0  # physically turned 90 deg from the 90 deg start
    p = odo.update(0.0, 0.0, dt_s=0.05)
    print(f"Check 2 (after reset()+90deg real turn): x={p.x:.3f} y={p.y:.3f} "
          f"yaw={math.degrees(p.yaw):.1f} (expect x~0.0, y~0.0, "
          f"yaw~-90.0 -- if this reads ~0.0 the heading reference is "
          f"WRONGLY re-locking on reset())")
